spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:/data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password: password